### ISSUE TITLE
Potentially nested Cargo dependency info

### ISSUE THREAD

**Issue by andrew** [librariesio/librarian#41]
https://libraries.io/github/qrlpx/qcollect

![screen shot 2015-09-21 at 10 12 54 am](https://cloud.githubusercontent.com/assets/1060/9988533/59f56e48-6049-11e5-9be7-8dd6c6faee54.png)

``` toml
[package]
name = "qcollect"
version = "0.4.0"
authors = ["qrlpx <>"]
keywords = ["data-structures", "collections"]

repository = "https://github.com/qrlpx/qcollect"
documentation = "https://qrlpx.github.io/qcollect/qcollect"
description = "Collections; Collection-Traits."

license = "CC0-1.0"

[dependencies]
raw-vec = "^0.1"
rustc-serialize = "^0.3.15"
qindex_multi = "^0.4"
qcollect-traits = { version = "0.4.0", path = "traits" }
#"^0.4"
```
